### PR TITLE
Generating updated document index

### PR DESCRIPTION
**Pull request by andygroff**
For some reason the site is only serving me boot.json style examples in the documentIndex file used for searching. There must be an environment related bug somewhere which I can't get to until this weekend but in the mean time here is an updated version of the full search index. Using this should restore search functionality until yarn run update is ran again.

### CODE REVIEW

**Comment by photonstorm** [comment]
Hmm true, hadn't even noticed this! It does it on both my PC and my Mac though!

**Comment by andygroff** [comment]
My best guess without much testing is you're using an older version of node that doesn't support Array.includes(). If that's the case a quick fix would be changing line 40 of `search/index-documents.js` to `if(excludedDirectories.indexOf(containingDirectory) > -1){`

The update command will print the number of files included in the index. If it's ~1300 then its all good.

image

**Comment by photonstorm** [comment]
Nope, I've debugged it a bit and it was simpler than that - the function `getContainingDirectory` assumed POSIX folder separator. Switched it out to use `path.sep` instead and it works fine now. New build pushed up.

**Comment by andygroff** [comment]
Awesome, that totally makes sense. Thanks for debugging it! I'm in the middle of an all-nighter to hit a work deadline in phaser so i'm trying not to go off on too many tangents :)

**Pull request closed without merging**
