### PR TITLE
Add fn names to tween ease equations example

### PR DESCRIPTION
**Pull request by 2007heaven**
#### Motivation

So that each name is mapped to each equation w/ less cognitive effort.

#### Output Snapshot
image

### CODE REVIEW

**Comment by ReydVires** [comment]
https://github.com/photonstorm/phaser3-examples/pull/298
Hope they approving this +1

**Comment by 2007heaven** [comment]
There's not that much complexity in approving an examples change that will aid understanding of the api so I really don't understand the delay. People seem to be using this examples page as a reference.

Another valid contribution, specifically to the phaser3 code, would be to add tween config ease fn name autocomplete by typing the `ease` property of the tween config object with a union type of a string enum of built-in ease fn names and a string (i.e: `EaseFnName | string`). The one used as a parameter of the `add` tween factory in the example.

I've stumbled upon other areas with lack of typing so if someone is interested in making a positive impact and in bolstering productivity of this framework's users they definitely have pending tasks waiting to be discovered.

**Comment by 2007heaven** [comment]
I'm using this framework heavily myself and I'm willing to volunteer at least in reviewing prs to an extent.

**Comment by jrabek** [comment]
omg yes.  This is definitely needed since it is a frequently used page for me.

Only suggestion would be to show the names on both sides.

```
        const ease = eases.shift();
        _this.add.text(100, child.y - 10, ease, {fontSize: "16px"})
        _this.add.text(600, child.y - 10, ease, {fontSize: "16px"})
        _this.tweens.add({
            targets: child,
            x: 700,
            ease,
            duration: 1500,
            delay: 1000,
            repeat: -1,
            repeatDelay: 1000,
            hold: 1000
        });
```

**Comment by 2007heaven** [comment]
@photonstorm The change seems to be useful to the people who are using transitions frequently judging by the like count and the discussion.

**Pull request merged**
