### PR TITLE
Fixed Y inverted light direction in the simple lights example

### PR DESCRIPTION
**Pull request by hexus**
This was bugging me in the lovely simple lights example.

There's probably a better way -  I haven't spent much time working out why this is happening - but this fixes it.

### CODE REVIEW

**Comment by hexus** [comment]
I think the best fix for this is actually in the normal generator. Inverting the Y component of `v_tex_coord` for the output arrives at the same result without introducing that ugly line in the light shader.

I can push a change for this, but honestly either is fine: it looks correct. :)

**Comment by hexus** [comment]
This might actually be caused by photonstorm/phaser#3137!

**Comment by photonstorm** [comment]
Sorry, forgot this was still open! Am closing off for now (because render pass has gone of course)

**Comment by hexus** [comment]
No worries 😁

**Pull request closed without merging**
